// flow-typed signature: dde6a2e1309951bb495cbad51b333d93
// flow-typed version: <<STUB>>/device-detect.js_v^0.2.7/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'device-detect.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'device-detect.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'device-detect.js/gruntfile' {
  declare module.exports: any;
}

declare module 'device-detect.js/lib/device' {
  declare module.exports: any;
}

declare module 'device-detect.js/lib/device.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'device-detect.js/gruntfile.js' {
  declare module.exports: $Exports<'device-detect.js/gruntfile'>;
}
declare module 'device-detect.js/lib/device.js' {
  declare module.exports: $Exports<'device-detect.js/lib/device'>;
}
declare module 'device-detect.js/lib/device.min.js' {
  declare module.exports: $Exports<'device-detect.js/lib/device.min'>;
}
