// flow-typed signature: 4e3aa0b880f063baaeb44eaa141e7c0a
// flow-typed version: <<STUB>>/postcss-css-reset_v^1.0.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-css-reset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-css-reset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-css-reset/lib/index' {
  declare module.exports: any;
}

declare module 'postcss-css-reset/lib/resetCore' {
  declare module.exports: any;
}

declare module 'postcss-css-reset/src/index' {
  declare module.exports: any;
}

declare module 'postcss-css-reset/src/resetCore' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-css-reset/lib/index.js' {
  declare module.exports: $Exports<'postcss-css-reset/lib/index'>;
}
declare module 'postcss-css-reset/lib/resetCore.js' {
  declare module.exports: $Exports<'postcss-css-reset/lib/resetCore'>;
}
declare module 'postcss-css-reset/src/index.js' {
  declare module.exports: $Exports<'postcss-css-reset/src/index'>;
}
declare module 'postcss-css-reset/src/resetCore.js' {
  declare module.exports: $Exports<'postcss-css-reset/src/resetCore'>;
}
