// flow-typed signature: 9424f6c1a8460052685585cbbcddb13f
// flow-typed version: <<STUB>>/postcss-mixins_v^5.2.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-mixins'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-mixins' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-mixins/index' {
  declare module.exports: $Exports<'postcss-mixins'>;
}
declare module 'postcss-mixins/index.js' {
  declare module.exports: $Exports<'postcss-mixins'>;
}
