// environment
export const CURRENT_DEVICE = 'CURRENT_DEVICE';
export const CHANGE_WIDTH_OR_HEIGHT_WINDOW = 'CHANGE_WIDTH_OR_HEIGHT_WINDOW';

// layout
export const CHANGE_MESSAGE_PANEL_HEIGHT = 'CHANGE_MESSAGE_PANEL_HEIGHT';

// interlocutor
export const CHANGE_CURRENT_INTERLOCUTOR = 'CHANGE_CURRENT_INTERLOCUTOR';
